USE STUDY

/*
	DROP TABLE IF EXISTS BINANCE_BOT_EVENT
	DROP TABLE IF EXISTS BINANCE_BOT_RESPONSE
*/

CREATE TABLE BINANCE_BOT_EVENT (
	ID bigint IDENTITY(1, 1) NOT NULL,

	[TYPE] varchar(50) NOT NULL,
	[TIMESTAMP] bigint NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__BINANCE_BOT_EVENT__CREATED_AT DEFAULT GETDATE(),
	PAYLOAD nvarchar(4000),

	CONSTRAINT PK__BINANCE_BOT_EVENT__ID PRIMARY KEY (ID)
)

CREATE TABLE BINANCE_BOT_RESPONSE (
	ID bigint IDENTITY(1, 1) NOT NULL,

	CORRELATION_ID varchar(50),
	[STATUS] int NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__BINANCE_BOT_RESPONSE__CREATED_AT DEFAULT GETDATE(),
	PAYLOAD nvarchar(4000),

	CONSTRAINT PK__BINANCE_BOT_RESPONSE__ID PRIMARY KEY (ID)
)
