CREATE DATABASE STUDY

USE STUDY

CREATE TABLE SYMBOL (
	ID bigint IDENTITY(1, 1) NOT NULL,
	[NAME] varchar(20) NOT NULL,
	BASE_ASSET_NAME varchar(10) NOT NULL,
	BASE_ASSET_PRECISION integer NOT NULL,
	QUOTE_ASSET_NAME varchar(10) NOT NULL,
	QUOTE_ASSET_PRECISION integer NOT NULL,
	IS_ICEBERG_ALLOWED bit NOT NULL,
	IS_OCO_ALLOWED bit NOT NULL,
	IS_SPOT_TRADING_ALLOWED bit NOT NULL,
	IS_MARGIN_TRADING_ALLOWED bit NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__SYMBOL__CREATED_AT DEFAULT GETDATE(),

	CONSTRAINT PK__SYMBOL__ID PRIMARY KEY (ID),
	CONSTRAINT UQ__SYMBOL__NAME UNIQUE ([NAME]),
	CONSTRAINT UQ__SYMBOL__BASE_ASSET_NAME__QUOTE_ASSET_NAME UNIQUE (BASE_ASSET_NAME, QUOTE_ASSET_NAME)
)

CREATE TABLE SYMBOL_KLINE (
	ID bigint IDENTITY(1, 1) NOT NULL,
	SYMBOL_ID bigint NOT NULL,

	TRADE_COUNT integer NOT NULL,
	OPEN_VALUE decimal(18, 8) NOT NULL,
	HIGH_VALUE decimal(18, 8) NOT NULL,
	LOW_VALUE decimal(18, 8) NOT NULL,
	CLOSE_VALUE decimal(18, 8) NOT NULL,
	BASE_ASSET_VOLUME decimal(18, 8) NOT NULL,
	BASE_ASSET_TAKER_BUY_VOLUME decimal(18, 8) NOT NULL,
	QUOTE_ASSET_VOLUME decimal(18, 8) NOT NULL,
	QUOTE_ASSET_TAKER_BUY_VOLUME decimal(18, 8) NOT NULL,
	OPEN_TIMESTAMP bigint NOT NULL,
	CLOSE_TIMESTAMP bigint NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__SYMBOL_KLINE__CREATED_AT DEFAULT GETDATE(),

	CONSTRAINT PK__SYMBOL_KLINE__ID PRIMARY KEY (ID),
	CONSTRAINT FK__SYMBOL_KLINE__SYMBOL_ID FOREIGN KEY (SYMBOL_ID) REFERENCES SYMBOL(ID),
	INDEX IX__SYMBOL_KLINE__SYMBOL_ID (SYMBOL_ID)
)
