CREATE DATABASE STUDY

USE STUDY

CREATE TABLE SYMBOL (
	ID bigint IDENTITY(1, 1) NOT NULL,
	[NAME] varchar(20) NOT NULL,
	BASE_ASSET_NAME varchar(10) NOT NULL,
	BASE_ASSET_PRECISION integer NOT NULL,
	QUOTE_ASSET_NAME varchar(10) NOT NULL,
	QUOTE_ASSET_PRECISION integer NOT NULL,
	IS_ICEBERG_ALLOWED bit NOT NULL,
	IS_OCO_ALLOWED bit NOT NULL,
	IS_SPOT_TRADING_ALLOWED bit NOT NULL,
	IS_MARGIN_TRADING_ALLOWED bit NOT NULL,
	CREATED_AT datetime NOT NULL CONSTRAINT DF__SYMBOL__CREATED_AT DEFAULT GETDATE(),

	CONSTRAINT PK__SYMBOL__ID PRIMARY KEY (ID),
	CONSTRAINT UQ__SYMBOL__NAME UNIQUE ([NAME]),
	CONSTRAINT UQ__SYMBOL__BASE_ASSET_NAME__QUOTE_ASSET_NAME UNIQUE (BASE_ASSET_NAME, QUOTE_ASSET_NAME)
)
