USE STUDY

/*
	DROP FUNCTION IF EXISTS FROM_UNIX_TIMESTAMP
*/

CREATE FUNCTION FROM_UNIX_TIMESTAMP (@TIMESTAMP AS bigint)
RETURNS datetime2
AS
BEGIN
	RETURN DATEADD(MILLISECOND, @TIMESTAMP % 1000, DATEADD(SECOND, (@TIMESTAMP / 1000) % 60, DATEADD(MINUTE, ((@TIMESTAMP / 1000) / 60) % 60, DATEADD(HOUR, ((@TIMESTAMP / 1000) / 60) / 60, CAST('1970-01-01' AS datetime2)))))
END
